### ISSUE TITLE
是否能够增加一个聊天框图标反色的功能以提高可读性呢

### ISSUE THREAD

**Issue by Alahjarko** [SyrieYume/starrail_ui#3]
![image](https://github.com/SyrieYume/starrail_ui/assets/143304950/fff5aa82-74ef-44a8-96c9-48bea60a5975)
在背景透明度高的时候，这些图标会和背景融为一体（黑暗模式下）。调成白天模式后，左侧的用户栏的字就看不清了，希望可以考虑一下

**Comment by SyrieYume** [comment]
我在 0.1.1 版本将这些图标的颜色改成了不透明的深色。
当窗口不透明度非常低，并且背景图片为深色的时候，这些图标会看不清。
如果把这些图标和背景的混合模式改成反色的话，虽然可以解决这个问题，但会导致图标颜色不均匀。

你可以自己修改插件中的 src/style.css 文件，这个颜色在第228行的位置。
比如你希望把这些图标改成白色，就修改为
``` css
/* 输入区域上方的工具图标，比如表情，文件，截图按钮 */
.chat-func-bar .q-icon, .func-bar .q-icon{
    color: rgb(255,255,255) !important;
}
```
或者直接在文件末尾加上上面的代码也行。
修改完文件并保存后，重启QQ就能看到效果了。
